# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a36e0c5d115417dca7c1c5f25900521791af884d788c73b80ebdf1fce69078bc116dc582025497e4969fce426cc279caa0f38944279be69a7671cf30611b56d1

test:
  secret_key_base: 4814247fc8bc391495605e746a912b4c066c8bd795f51ceb093cd76f09dd2646cd382ccd8edff1e9f43b0704a0e646c667e3ae05a1a99c29e596b42addb23695

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
